export const CART_ADD_ITEM='CART_ADD_ITEM'
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM'
export const CART_QUANTITY_INCREMENT='CART_QUANTITY_INCREMENT'
export const CART_QUANTITY_DECREMENT='CART_QUANTITY_DECREMENT'